// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.9

import 'dart:core';
import 'package:flutter_ui/core/models/entity.dart' as prefix0;
import 'package:flutter_ui/core/models/operationClaim/operationClaimAddModel.dart'
    as prefix3;
import 'package:flutter_ui/core/models/translate/translateAddModel.dart'
    as prefix1;
import 'package:flutter_ui/core/models/translate/translateModel.dart'
    as prefix2;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Entity(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'TranslateAddModel',
            r'.TranslateAddModel',
            7,
            0,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (languageId, key, value) =>
                  b ? prefix1.TranslateAddModel(languageId, key, value) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'languageId': 0,
              r'languageId=': 1,
              r'key': 0,
              r'key=': 1,
              r'value': 0,
              r'value=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'TranslateModel',
            r'.TranslateModel',
            7,
            1,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (id, languageId, key, value) =>
                  b ? prefix2.TranslateModel(id, languageId, key, value) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix2.TranslateModel.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'id': 0,
              r'id=': 1,
              r'languageId': 0,
              r'languageId=': 1,
              r'key': 0,
              r'key=': 1,
              r'value': 0,
              r'value=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'OperationClaimAddModel',
            r'.OperationClaimAddModel',
            7,
            2,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  (name) => b ? prefix3.OperationClaimAddModel(name) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'name': 0,
              r'name=': 1
            })
      ],
      null,
      null,
      <Type>[
        prefix1.TranslateAddModel,
        prefix2.TranslateModel,
        prefix3.OperationClaimAddModel
      ],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'languageId': (dynamic instance) => instance.languageId,
        r'key': (dynamic instance) => instance.key,
        r'value': (dynamic instance) => instance.value,
        r'id': (dynamic instance) => instance.id,
        r'name': (dynamic instance) => instance.name
      },
      {
        r'languageId=': (dynamic instance, value) =>
            instance.languageId = value,
        r'key=': (dynamic instance, value) => instance.key = value,
        r'value=': (dynamic instance, value) => instance.value = value,
        r'id=': (dynamic instance, value) => instance.id = value,
        r'name=': (dynamic instance, value) => instance.name = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null],
        const [3, 0, null],
        const [4, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
