// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.9

import 'dart:core';
import 'package:flutter_ui/core/models/entity.dart' as prefix0;
import 'package:flutter_ui/core/models/operationClaim/operationClaimAddModel.dart'
    as prefix5;
import 'package:flutter_ui/core/models/operationClaim/operationClaimDetailsModel.dart'
    as prefix8;
import 'package:flutter_ui/core/models/operationClaim/operationClaimModel.dart'
    as prefix10;
import 'package:flutter_ui/core/models/translate/translateAddModel.dart'
    as prefix1;
import 'package:flutter_ui/core/models/translate/translateModel.dart'
    as prefix2;
import 'package:flutter_ui/core/models/user/loginModel.dart' as prefix3;
import 'package:flutter_ui/core/models/user/registerModel.dart' as prefix7;
import 'package:flutter_ui/core/models/user/tokenModel.dart' as prefix6;
import 'package:flutter_ui/core/models/user/userAddModel.dart' as prefix9;
import 'package:flutter_ui/core/models/user/userModel.dart' as prefix4;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Entity(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'TranslateAddModel',
            r'.TranslateAddModel',
            7,
            0,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (languageId, key, value) =>
                  b ? prefix1.TranslateAddModel(languageId, key, value) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'languageId': 0,
              r'languageId=': 1,
              r'key': 0,
              r'key=': 1,
              r'value': 0,
              r'value=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'TranslateModel',
            r'.TranslateModel',
            7,
            1,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (id, languageId, key, value) =>
                  b ? prefix2.TranslateModel(id, languageId, key, value) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix2.TranslateModel.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'id': 0,
              r'id=': 1,
              r'languageId': 0,
              r'languageId=': 1,
              r'key': 0,
              r'key=': 1,
              r'value': 0,
              r'value=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'LoginModel',
            r'.LoginModel',
            7,
            2,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (email, password) =>
                  b ? prefix3.LoginModel(email, password) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'email': 0,
              r'email=': 1,
              r'password': 0,
              r'password=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'UserModel',
            r'.UserModel',
            7,
            3,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (id, firstName, lastName, email, status) => b
                  ? prefix4.UserModel(id, firstName, lastName, email, status)
                  : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix4.UserModel.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'id': 0,
              r'id=': 1,
              r'firstName': 0,
              r'firstName=': 1,
              r'lastName': 0,
              r'lastName=': 1,
              r'email': 0,
              r'email=': 1,
              r'status': 0,
              r'status=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'OperationClaimAddModel',
            r'.OperationClaimAddModel',
            7,
            4,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) =>
                  (name) => b ? prefix5.OperationClaimAddModel(name) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'name': 0,
              r'name=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'TokenModel',
            r'.TokenModel',
            7,
            5,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (token, expiration) =>
                  b ? prefix6.TokenModel(token, expiration) : null,
              r'fromJson': (bool b) =>
                  (json) => b ? prefix6.TokenModel.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'token': 0,
              r'token=': 1,
              r'expiration': 0,
              r'expiration=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'RegisterModel',
            r'.RegisterModel',
            7,
            6,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (firstName, lastName, email, password) => b
                  ? prefix7.RegisterModel(firstName, lastName, email, password)
                  : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'firstName': 0,
              r'firstName=': 1,
              r'lastName': 0,
              r'lastName=': 1,
              r'email': 0,
              r'email=': 1,
              r'password': 0,
              r'password=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'OperationClaimDetailsModel',
            r'.OperationClaimDetailsModel',
            7,
            7,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (id, claims, firstName, lastName, email) => b
                  ? prefix8.OperationClaimDetailsModel(
                      id, claims, firstName, lastName, email)
                  : null,
              r'fromJson': (bool b) => (json) =>
                  b ? prefix8.OperationClaimDetailsModel.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'id': 0,
              r'id=': 1,
              r'claims': 0,
              r'claims=': 1,
              r'firstName': 0,
              r'firstName=': 1,
              r'lastName': 0,
              r'lastName=': 1,
              r'email': 0,
              r'email=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'UserAddModel',
            r'.UserAddModel',
            7,
            8,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (firstName, lastName, email, status) => b
                  ? prefix9.UserAddModel(firstName, lastName, email, status)
                  : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'firstName': 0,
              r'firstName=': 1,
              r'lastName': 0,
              r'lastName=': 1,
              r'email': 0,
              r'email=': 1,
              r'status': 0,
              r'status=': 1
            }),
        r.NonGenericClassMirrorImpl(
            r'OperationClaimModel',
            r'.OperationClaimModel',
            7,
            9,
            const prefix0.Entity(),
            const <int>[-1],
            null,
            null,
            -1,
            {},
            {},
            {
              r'': (bool b) => (id, name) =>
                  b ? prefix10.OperationClaimModel(id, name) : null,
              r'fromJson': (bool b) => (json) =>
                  b ? prefix10.OperationClaimModel.fromJson(json) : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            {
              r'==': 1,
              r'toString': 0,
              r'noSuchMethod': 1,
              r'hashCode': 0,
              r'runtimeType': 0,
              r'toJson': 0,
              r'id': 0,
              r'id=': 1,
              r'name': 0,
              r'name=': 1
            })
      ],
      null,
      null,
      <Type>[
        prefix1.TranslateAddModel,
        prefix2.TranslateModel,
        prefix3.LoginModel,
        prefix4.UserModel,
        prefix5.OperationClaimAddModel,
        prefix6.TokenModel,
        prefix7.RegisterModel,
        prefix8.OperationClaimDetailsModel,
        prefix9.UserAddModel,
        prefix10.OperationClaimModel
      ],
      10,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'toJson': (dynamic instance) => instance.toJson,
        r'languageId': (dynamic instance) => instance.languageId,
        r'key': (dynamic instance) => instance.key,
        r'value': (dynamic instance) => instance.value,
        r'id': (dynamic instance) => instance.id,
        r'email': (dynamic instance) => instance.email,
        r'password': (dynamic instance) => instance.password,
        r'firstName': (dynamic instance) => instance.firstName,
        r'lastName': (dynamic instance) => instance.lastName,
        r'status': (dynamic instance) => instance.status,
        r'name': (dynamic instance) => instance.name,
        r'token': (dynamic instance) => instance.token,
        r'expiration': (dynamic instance) => instance.expiration,
        r'claims': (dynamic instance) => instance.claims
      },
      {
        r'languageId=': (dynamic instance, value) =>
            instance.languageId = value,
        r'key=': (dynamic instance, value) => instance.key = value,
        r'value=': (dynamic instance, value) => instance.value = value,
        r'id=': (dynamic instance, value) => instance.id = value,
        r'email=': (dynamic instance, value) => instance.email = value,
        r'password=': (dynamic instance, value) => instance.password = value,
        r'firstName=': (dynamic instance, value) => instance.firstName = value,
        r'lastName=': (dynamic instance, value) => instance.lastName = value,
        r'status=': (dynamic instance, value) => instance.status = value,
        r'name=': (dynamic instance, value) => instance.name = value,
        r'token=': (dynamic instance, value) => instance.token = value,
        r'expiration=': (dynamic instance, value) =>
            instance.expiration = value,
        r'claims=': (dynamic instance, value) => instance.claims = value
      },
      null,
      [
        const [0, 0, null],
        const [1, 0, null],
        const [3, 0, null],
        const [4, 0, null],
        const [2, 0, null],
        const [5, 0, null]
      ])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
